name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Android SDK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android
          rm commandlinetools-linux-7583922_latest.zip
          yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
          $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platforms;android-33" "build-tools;33.0.0"
          $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "tools"

      - name: Set environment variables for Android SDK
        run: echo "ANDROID_HOME=$HOME/Android" >> $GITHUB_ENV

      - name: Add Android SDK to PATH
        run: |
          echo "$HOME/Android/cmdline-tools/bin" >> $GITHUB_PATH
          echo "$HOME/Android/platform-tools" >> $GITHUB_PATH

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --warning-mode all --info --debug
