name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Clean Gradle cache to avoid issues with caching
      - name: Clean Gradle cache
        run: rm -rf ~/.gradle/caches/

      # Ensure gradlew has executable permission
      - name: Ensure gradlew has executable permission
        run: chmod +x gradlew

      # Download and install Gradle wrapper if missing
      - name: Download Gradle Wrapper
        run: |
          if [ ! -f gradlew ]; then
            echo "gradlew not found, generating it..."
            curl -sSL https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -o gradle.zip
            unzip gradle.zip
            mv gradle-7.4.2 gradle
            chmod +x gradle/bin/gradle
          fi

      # Run Gradle build task with debug output
      - name: Build the app
        run: ./gradlew assembleDebug --stacktrace --warning-mode all --info --debug
